services:

  nginx:
    container_name: rithmo-skeleton-nginx
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./app:/app"
    ports:
      - "${PORT_NGINX}:80"
    depends_on:
      - php

  php:
    container_name: rithmo-skeleton-php
    user: "${WORKSPACE_PUID}:${WORKSPACE_PGID}"
    volumes:
      - "./app:/app"
      - "./temporary/composer/cache:/.composer/cache"
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - PUID=${WORKSPACE_PUID}
        - PGID=${WORKSPACE_PGID}
        - TZ=${WORKSPACE_TIMEZONE}
    restart: on-failure
    env_file:
      - .env
    environment:
      COMPOSER_MEMORY_LIMIT: -1